### PR TITLE
Supress 'use strict/warnings pragma' for common Test2 includes

### PR DESCRIPTION
**Pull request by jbakerdev**
* Suppress "use strict/warnings pragma"

There are other relevant Test2 bundles, but since this is my first PR for the project I'm starting small - hopefully this is an appropriate solution, if not I can re-work it.

### CODE REVIEW

**Comment by jbakerdev** [comment]
Refactored and added support for additional Test2 libraries. Added tests (cribbing from existing code)

**Comment by jbakerdev** [comment]
Related to issue #2340

**Comment by jbakerdev** [comment]
@hurricup do you have any feedback for this?

**Comment by hurricup** [comment]
Sorry, I was away from my computer and internet for some time. Will check this as soon as I can.

**Comment by jbakerdev** [comment]
@hurricup anything you need from me on this?

**Comment by hurricup** [comment]
Nope. Digging through my debts.

**Comment by hurricup** [comment]
Thanks for your implementation, I've adjusted it and pushed.

**Pull request closed without merging**
