### PR TITLE
Add conversion of foreach to for Intention

### PR DESCRIPTION
**Pull request by brnrc**
This intention will be available only when the `foreach` has a lexical variable declaration in it. This is to avoid cases where `foreach` uses the default variable `$_`.
e.g `my $path`:
```perl
foreach my $path (@INC) {
    print "$path\n";
}
```

### CODE REVIEW

**Comment by hurricup** [comment]
Would be nice if you could fix this today/tomorrow. Release is coming...

**Comment by brnrc** [comment]
Thanks man! 😅
I fixed the detection with your suggestion (way simpler btw). But I don't think I'll be able to implement the CodeStyle changes until next Monday. There are a few other improvements I would like to build upon this first version, as suggesting the `@list` variable name and proper position of the caret after applying the conversion. 
If you think it is ok to add this new Intention, as is, in this release, and update it in the upcoming releases, feel free to do it.

**Comment by hurricup** [comment]
Thank you! I mean - reformat your java code according to project's style. :)
Perl code style will be re-worked in next version, so don't bother.

**Comment by hurricup** [comment]
I've merged PR, thank you. In future:
1. Use project CodeStyle for your code
2. Set up copyright

**Comment by hurricup** [comment]
Also, just an idea:  you could enable intetion on any element inside the foreach loop. Just try to find foreach parent and check if it's correct.

**Comment by hurricup** [comment]
You also should check a filetype i guess. Because your intention will be enabled in let's say Mojolicious, but won't work, if there is template part inside. like:

```
% foreach my $var (@list){
<div>...</div>
% }

**Pull request merged**
