### PR TITLE
wip

### PR DESCRIPTION
**Pull request by ikenox**
update

update

### CODE REVIEW

**Comment by hurricup** [comment]
I suggest to discuss this. Could you describe your idea?

**Comment by ikenox** [comment]
@hurricup 

I'm sorry that I made the pull request of WIP branch by mistake.
This pull request is now work in progress and I'll make a pull request again after some remained problems resolved.

The following is a description of this pull request. I would appreciate your advice for improvement.

## About this pull request

This pull request mainly resolves #254, type detection of ArrayRef and HashRef.
Currently this plugin stores detected variable types into String values.
But String can't be used for storing structured type information.

So, instead of using String values for storing type information, I use instances of `PerlType` based classes.
So, if the plugin detect a type `ArrayRef[SomeClass]`, type information are stored into a instance of `PerlTypeArrayRef`, and we can get the wrapped type `SomeClass` from the instance anytime.

Implementation is almost done and tests are also almost passed, but some problems are remained.

## Remained problems

This pull request contains not only the feature of #254 but also many other type detection features.
Type of the following variables will be detected.

- iteration variables in map/sort/grep statement
- iteration variables in for/foreach statemnt
- elements of ArrayRef
- and so on

These features should be separated into different commits and different pull requests.

And more, some my dirty implementation and bad named class/subs/variables are remained. I have to do some refactoring.

**Comment by hurricup** [comment]
Ok. I've started on the same thing myself, but proper support of such things like complex types, requires a control flow. And it is in development. See `control-flow` branch. So I suggest to postpone your work until it merged into master. 
The main idea of my approach not only to make support for array/hash and so on, but to be able to describe complex computations and store them as return values.
E.g.:
Foo.pm
```
sub Foo::foo{
      return +{bazval => baz_getter()};
}
```
Bar.pm
```
sub Bar::bar{
      my $foo = Foo::foo();
       ... ; #some code here
       return $foo->{bazval};
}
```
Plugin should be able to compute and serialize return value for `Bar::bar` something like:
```
 #@returns RetVal[Foo::foo]->{bazval}
```
This makes return value of `Bar::bar` explicitly depends on `Bar::bar` code only. And external things are delegated by foreign methods FQNs. And some symbolic execution should be able to resolve this computation, find `baz_getter` in the end and find what it returns.

**Comment by ikenox** [comment]
That sounds better idea and looks like to have more rich features than mine. Ok, I postpone my work.
Thank you for your explanation and I’m looking forward to your work :)

**Pull request closed without merging**
