### PR TITLE
Handle multiline chained map grep sort etc.

### PR DESCRIPTION
**Pull request by jonas-lindmark**
Just a first attempt at this, there may be other things involved here I do not understand, but think no tests are broken at least. Maybe add a formatting setting to toggle this feature on and off if it causes problem somewhere else or just give user control.

Did a quick performance test running all unit tests under plugin/test/formatter and could not see any difference, around 1m 47s both.

### CODE REVIEW

**Comment by jonas-lindmark** [comment]
Looks like some tests broke after all, having problem reading output from CI build but seems like these tests are failing:

liveTemplates.PerlLiveTemplatesTest.testSub
completion.PerlCompletionTest.testUnicodeNames

Will have to look at those if we would like to continue with this.

**Comment by hurricup** [comment]
Sorry for delay, was away from my computer and internet for some time. Will check this as soon as I can. Thanks.

**Comment by jonas-lindmark** [comment]
After using my implementation as it is here in PR on one computer (side by side with stock plugin on other/laptop) fore some time there is some cases that is not handled correctly still. From the top of my head:
- New line directly after assignment
- First symbol in chain is function call, List::Util::first etc.

Also noted improvement in other constructs, the following moose type declarations are formated according to the [documentation](https://metacpan.org/pod/Moose::Util::TypeConstraints) :-) 
```perl
subtype 'NaturalLessThanTen',
    as 'Natural',
    where { $_ < 10 },
    message { "This number ($_) is not less than ten!" };

coerce 'Num',
    from 'Str',
    via { 0 + $_ };
```

**Comment by hurricup** [comment]
Could you please rebase this on current master and force push it to the branch?

**Comment by jonas-lindmark** [comment]
Sorry did not see your message until now. A little unsure about the github workflow but think i manage to merge from upstream, diff looks okay so hope it's fine without a proper rebase.

**Comment by hurricup** [comment]
If you not objecting I'd take your code, optimize it a bit and push. This gonna be faster then reviews and fixes. Or we can go on :)

**Comment by jonas-lindmark** [comment]
Absolutely, I'm mostly interested in getting the feature implemented so please go ahead :-)

**Comment by hurricup** [comment]
Sorry it took so long. Implemented your approach, except the array/slices/etc. Technically anything may be in the end, so still unclear if we should align that tail.

**Pull request closed without merging**
