### PR TITLE
Add HTTP-Tiny and JSON-PP

### PR DESCRIPTION
**Pull request by rwp0**
HTTP::Tiny, JSON::PP, JSON::PP::Boolean are Perl core modules

I think this should make their names **bold** in the editor (*as with `Term::ANSIColor`*) as a hint.

image

Perldoc contains documentation only for core modules, unlike CPAN/MetaCPAN.

https://perldoc.perl.org/modules
https://perldoc.perl.org/HTTP::Tiny
https://perldoc.perl.org/JSON::PP
https://perldoc.perl.org/JSON::PP::Boolean

### CODE REVIEW

**Comment by hurricup** [comment]
Would be nice to make it like 'Core packages update to version ...' not only add these particular modules.

**Comment by hurricup** [comment]
Okay, there is a security issue with secrets for PR. I'll get back to this later.

**Comment by rwp0** [comment]
> Would be nice to make it like 'Core packages update to version ...' not only add these particular modules.

Feel free to amend the title

**Comment by hurricup** [comment]
What version is this from and are these all packages missing?

**Comment by hurricup** [comment]
Could you please re-word commit message and force push your branch, so we could check if updated workflow for PR would work properly?

**Comment by rwp0** [comment]
I can resubmit this PR if needed.

Not sure on the version of Perl these modules were added in, can check with `corelist` if that matters.

These modules are "missing" in that so their names are not bold when `use`d inside IDE.

**Comment by rwp0** [comment]
I can resubmit this PR if needed.

Not sure on the version of Perl these modules were added in, can check with `corelist` if that matters.

These modules are "missing" in that so their names are not bold when `use`d inside IDE.

**Comment by hurricup** [comment]
I mean if you want to update the list, don't just add few you noticed, but update list to the state of 5.36, for example

**Comment by rwp0** [comment]
Alright, will look into that.

I just prefer to do things gradually 🙂

**Comment by hurricup** [comment]
Yes, but it is better to keep things consistent with some perl versions

**Pull request merged**
